import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.1";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

// Resolve assignment group name → ID (Canvas API)
async function resolveGroupId(
  courseBase: string,
  headers: HeadersInit,
  groupName: string
): Promise<number | null> {
  const res = await fetchWithRetry(`${courseBase}/assignment_groups`, { headers });
  if (!res.ok) { await res.text(); return null; }
  const groups = await res.json();
  const match = groups.find((g: { name: string }) => g.name === groupName);
  return match ? match.id : null;
}

// DST-aware ET → UTC conversion. dateStr = YYYY-MM-DD; sets due to 23:59 America/New_York.
function toDueAt(dateStr: string): string {
  // Determine offset for that date in America/New_York via shortOffset (e.g. "GMT-4" / "GMT-5")
  const probe = new Date(`${dateStr}T12:00:00Z`);
  const fmt = new Intl.DateTimeFormat('en-US', {
    timeZone: 'America/New_York',
    timeZoneName: 'shortOffset',
  });
  const parts = fmt.formatToParts(probe);
  const tzPart = parts.find((p) => p.type === 'timeZoneName')?.value || 'GMT-5';
  const match = tzPart.match(/GMT([+-])(\d{1,2})/);
  const sign = match?.[1] === '+' ? '+' : '-';
  const hours = match?.[2]?.padStart(2, '0') || '05';
  const offset = `${sign}${hours}:00`;
  const local = new Date(`${dateStr}T23:59:00${offset}`);
  return local.toISOString();
}

async function fetchWithRetry(url: string, init: RequestInit, attempts = 3): Promise<Response> {
  let lastErr: Error | null = null;
  for (let i = 0; i < attempts; i++) {
    try {
      const res = await fetch(url, init);
      if (res.status >= 500 || res.status === 429) {
        if (i < attempts - 1) {
          await new Promise((r) => setTimeout(r, 400 * Math.pow(2, i)));
          continue;
        }
      }
      return res;
    } catch (e) {
      lastErr = e as Error;
      if (i < attempts - 1) await new Promise((r) => setTimeout(r, 400 * Math.pow(2, i)));
    }
  }
  throw lastErr ?? new Error('fetchWithRetry exhausted');
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const {
      subject, courseId, title, description, points, gradingType,
      assignmentGroup, dueDate, existingId, rowId, weekId,
      omitFromFinal, contentHash,
      day, type, isSynthetic,
      force,
    } = await req.json();

    if (!courseId || !title) {
      return new Response(JSON.stringify({ error: "Missing courseId or title" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const canvasToken = Deno.env.get("CANVAS_API_TOKEN");
    let canvasBase = Deno.env.get("CANVAS_BASE_URL") || "https://thalesacademy.instructure.com";
    if (!canvasBase.startsWith("http")) canvasBase = `https://${canvasBase}`;
    canvasBase = canvasBase.replace(/\/+$/, "");
    if (!canvasToken) {
      return new Response(JSON.stringify({ error: "CANVAS_API_TOKEN not configured" }), {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const sb = createClient(supabaseUrl, supabaseKey);

    // ========= HARD BUSINESS-RULE GUARD (defense in depth) =========
    // Synthetic Math Triple rows (Fact Test, Study Guide) bypass these rules
    // because they are generated by the builder, not user-entered.
    // Hydrate from DB when callers (e.g., automation-friday-deploy) only sent rowId.
    let guardSubject = subject as string | undefined;
    let guardDay = day as string | undefined;
    let guardType = type as string | undefined;
    let guardSynthetic = isSynthetic as boolean | undefined;
    if (rowId && (guardSubject === undefined || guardDay === undefined || guardType === undefined || guardSynthetic === undefined)) {
      const { data: r } = await sb
        .from("pacing_rows")
        .select("subject, day, type, is_synthetic")
        .eq("id", rowId)
        .maybeSingle();
      if (r) {
        guardSubject = guardSubject ?? r.subject ?? undefined;
        guardDay = guardDay ?? r.day ?? undefined;
        guardType = guardType ?? r.type ?? undefined;
        guardSynthetic = guardSynthetic ?? r.is_synthetic ?? false;
      }
    }
    let blockedReason: string | null = null;
    if (!guardSynthetic && !force) {
      if (guardSubject === "History" || guardSubject === "Science") {
        blockedReason = `${guardSubject} — assignments are never created (rule)`;
      } else if (guardDay === "Friday" && guardType !== "Test") {
        blockedReason = "Friday — no homework assignments (rule)";
      } else if (
        guardSubject === "Language Arts" &&
        guardType && !["CP", "Classroom Practice", "Test"].includes(guardType)
      ) {
        blockedReason = "Language Arts — only CP and Test create assignments (rule)";
      }
    }

    // CLT / No-School Day Guard — block any assignment whose dueDate falls on a
    // non-instructional day (CLT testing window, holiday, track-out, teacher workday).
    // Synthetic rows and force=true bypass.
    if (!guardSynthetic && !force && dueDate && !blockedReason) {
      const { data: cal } = await sb
        .from("school_calendar")
        .select("event_type, label, cancels_instruction")
        .eq("date", dueDate)
        .maybeSingle();

      if (cal && cal.cancels_instruction === true) {
        const labelMap: Record<string, string> = {
          holiday:         "Holiday",
          track_out:       "Track Out",
          teacher_workday: "Teacher Workday",
          no_school:       "No School",
          half_day:        "Half Day",
          early_release:   "Early Release",
        };
        blockedReason = `${labelMap[cal.event_type] ?? cal.event_type} — non-instructional day (${cal.label})`;
      }
    }
    if (blockedReason) {
      await sb.from("deploy_log").insert({
        week_id: weekId || null,
        subject: guardSubject || null,
        action: "assignment_deploy",
        status: "BLOCKED",
        message: `${blockedReason}: ${title}`,
        payload: { day: guardDay, type: guardType, subject: guardSubject, title } as unknown as Record<string, unknown>,
      });
      await sb.from("deploy_notifications").insert({
        level: "warn",
        title: `Assignment blocked — ${guardSubject || ""}`,
        message: `${title} — ${blockedReason}`,
        entity_ref: rowId || null,
      });
      return new Response(JSON.stringify({ status: "BLOCKED", reason: blockedReason }), {
        status: 200,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }


    // ========= NO_CHANGE skip via content_hash =========
    if (rowId && contentHash) {
      const { data: existingRow } = await sb
        .from("pacing_rows")
        .select("content_hash, canvas_assignment_id, canvas_url")
        .eq("id", rowId)
        .maybeSingle();
      if (
        existingRow &&
        existingRow.content_hash === contentHash &&
        existingRow.canvas_assignment_id
      ) {
        await sb.from("deploy_log").insert({
          week_id: weekId || null,
          subject: subject || null,
          action: "assignment_deploy",
          status: "NO_CHANGE",
          canvas_url: existingRow.canvas_url,
          message: `Skipped (no change): ${title}`,
        });
        return new Response(JSON.stringify({
          status: "NO_CHANGE",
          assignmentId: existingRow.canvas_assignment_id,
          canvasUrl: existingRow.canvas_url,
        }), { headers: { ...corsHeaders, "Content-Type": "application/json" } });
      }
    }

    const canvasHeaders = {
      Authorization: `Bearer ${canvasToken}`,
      "Content-Type": "application/json",
    };

    const courseBase = `${canvasBase}/api/v1/courses/${courseId}`;
    const parseNextLink = (linkHeader: string | null): string | null => {
      if (!linkHeader) return null;
      const parts = linkHeader.split(",");
      for (const part of parts) {
        const match = part.match(/<([^>]+)>;\s*rel="next"/);
        if (match) return match[1];
      }
      return null;
    };

    const findAssignmentByExactName = async (
      exactName: string,
    ): Promise<{ id: string; htmlUrl: string | null } | null> => {
      let nextUrl: string | null =
        `${courseBase}/assignments?per_page=100&search_term=${encodeURIComponent(exactName)}`;
      let safety = 0;

      while (nextUrl && safety < 50) {
        const listRes = await fetchWithRetry(nextUrl, { headers: canvasHeaders });
        if (!listRes.ok) {
          const errText = await listRes.text();
          throw new Error(`Assignment lookup failed (${listRes.status}): ${errText}`);
        }
        const items = (await listRes.json()) as Array<{ id: number; name?: string; html_url?: string | null }>;
        const match = items.find((item) => item.name === exactName);
        if (match) {
          return { id: String(match.id), htmlUrl: match.html_url ?? null };
        }
        nextUrl = parseNextLink(listRes.headers.get("link"));
        safety += 1;
      }

      return null;
    };

    const assignmentExistsById = async (id: string): Promise<boolean> => {
      const res = await fetchWithRetry(`${courseBase}/assignments/${id}`, { headers: canvasHeaders });
      if (res.ok) return true;
      if (res.status === 404) return false;
      const errText = await res.text();
      throw new Error(`Assignment existence check failed (${res.status}): ${errText}`);
    };

    let groupId: number | null = null;
    if (assignmentGroup) {
      groupId = await resolveGroupId(courseBase, canvasHeaders, assignmentGroup);
    }

    const payload: Record<string, unknown> = {
      assignment: {
        name: title,
        description: description || "",
        points_possible: points ?? 100,
        grading_type: gradingType || "points",
        published: true,
        ...(groupId ? { assignment_group_id: groupId } : {}),
        ...(dueDate ? { due_at: toDueAt(dueDate) } : {}),
        ...(omitFromFinal ? { omit_from_final_grade: true } : {}),
      },
    };

    // Determine update vs create
    let canvasAssignmentId = existingId;
    if (!canvasAssignmentId && rowId) {
      const { data: row } = await sb
        .from("pacing_rows")
        .select("canvas_assignment_id")
        .eq("id", rowId)
        .maybeSingle();
      canvasAssignmentId = row?.canvas_assignment_id || null;
    }
    let discoveredAssignmentUrl: string | null = null;
    if (canvasAssignmentId) {
      const stillExists = await assignmentExistsById(canvasAssignmentId);
      if (!stillExists) {
        canvasAssignmentId = null;
      }
    }
    if (!canvasAssignmentId) {
      const existingAssignment = await findAssignmentByExactName(title);
      if (existingAssignment) {
        canvasAssignmentId = existingAssignment.id;
        discoveredAssignmentUrl = existingAssignment.htmlUrl;
      }
    }
    const isUpdate = !!canvasAssignmentId;
    const method = isUpdate ? "PUT" : "POST";
    const url = isUpdate
      ? `${courseBase}/assignments/${canvasAssignmentId}`
      : `${courseBase}/assignments`;

    const res = await fetchWithRetry(url, {
      method,
      headers: canvasHeaders,
      body: JSON.stringify(payload),
    });

    if (!res.ok) {
      const errText = await res.text();
      await sb.from("deploy_log").insert({
        week_id: weekId || null,
        subject: subject || null,
        action: "assignment_deploy",
        status: "ERROR",
        message: `${method} ${res.status}: ${errText}`,
        payload: payload,
      });
      await sb.from("deploy_notifications").insert({
        level: "error",
        title: `Assignment deploy failed: ${subject || ''}`,
        message: `${title} — ${res.status}`,
      });
      if (rowId) {
        await sb.from("pacing_rows").update({ deploy_status: "ERROR" }).eq("id", rowId);
      }
      return new Response(JSON.stringify({ error: errText, status: "ERROR" }), {
        status: 502,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const result = await res.json();
    const assignmentId = String(result.id);
    const canvasUrl = result.html_url ||
      discoveredAssignmentUrl ||
      `${canvasBase}/courses/${courseId}/assignments/${assignmentId}`;

    if (rowId) {
      await sb.from("pacing_rows").update({
        canvas_assignment_id: assignmentId,
        canvas_url: canvasUrl,
        deploy_status: "DEPLOYED",
        last_deployed: new Date().toISOString(),
        ...(contentHash ? { content_hash: contentHash } : {}),
      }).eq("id", rowId);
    }

    await sb.from("deploy_log").insert({
      week_id: weekId || null,
      subject: subject || null,
      action: "assignment_deploy",
      status: "DEPLOYED",
      canvas_url: canvasUrl,
      message: `${isUpdate ? "Updated" : "Created"} assignment: ${title}`,
    });
    await sb.from("deploy_notifications").insert({
      level: "success",
      title: `Assignment ${isUpdate ? "updated" : "deployed"}: ${subject || ''}`,
      message: title,
      entity_ref: canvasUrl,
    });

    return new Response(JSON.stringify({
      status: "DEPLOYED",
      assignmentId,
      canvasUrl,
    }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (e) {
    return new Response(JSON.stringify({ error: e instanceof Error ? e.message : "Unknown error" }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
